theme: jekyll-theme-minimal
title: BeerAdvocate.com, Leveraging User Tendencies to Improve User Experience
description: AnalyTeam, 2022
#show_downloads: True
#navigation:
#  - title: Home
#    url: /
#  - title: Bibliography
#    url: bibliography
