theme: jekyll-theme-minimal
title: Unveiling Character Dynamics of Movie Narratives
description: RollTheDataDice, 2023
#show_downloads: True
#navigation:
#  - title: Home
#    url: /
#  - title: Bibliography
#    url: bibliography
